"""Generates a self-contained HTML report from episode data."""

from datetime import datetime, timezone
from itertools import groupby
from pathlib import Path


# ---------------------------------------------------------------------------
# Source metadata (badge labels / icons)
# ---------------------------------------------------------------------------

_SOURCE_META = {
    "credit_edge":        {"label": "Bloomberg Intelligence", "icon": "📡"},
    "view_from_apollo":   {"label": "Apollo Global Mgmt",     "icon": "🔭"},
    "goldman_sachs":      {"label": "Goldman Sachs",           "icon": "▶"},
    "odd_lots":           {"label": "Bloomberg Odd Lots",      "icon": "🎙"},
    "oaktree_insight":    {"label": "Oaktree Capital",         "icon": "🌳"},
    "capital_allocators": {"label": "Capital Allocators",      "icon": "▶"},
}

# ---------------------------------------------------------------------------
# HTML skeleton
# ---------------------------------------------------------------------------

_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Finance Intelligence Weekly</title>
<style>
{css}
</style>
</head>
<body>
<header>
  <div class="header-inner">
    <div class="header-brand">
      <span class="brand-icon">◈</span>
      <div>
        <h1>Finance Intelligence</h1>
        <p class="tagline">Weekly briefings from Credit Edge · Odd Lots · Apollo · Oaktree · Goldman Sachs · Capital Allocators</p>
      </div>
    </div>
    <div class="header-meta">
      <span class="updated-label">Last updated</span>
      <span class="updated-date">{updated}</span>
    </div>
  </div>
</header>

<div class="controls">
  <div class="controls-inner">
    <div class="filter-group">
      <span class="filter-label">Filter by source</span>
      <div class="filter-btns">
        <button class="filter-btn active" data-source="all">All Sources</button>
        <button class="filter-btn" data-source="credit_edge">Credit Edge</button>
        <button class="filter-btn" data-source="odd_lots">Odd Lots</button>
        <button class="filter-btn" data-source="view_from_apollo">Apollo</button>
        <button class="filter-btn" data-source="oaktree_insight">Oaktree</button>
        <button class="filter-btn" data-source="goldman_sachs">Goldman Sachs</button>
        <button class="filter-btn" data-source="capital_allocators">Capital Allocators</button>
      </div>
    </div>
    <div class="stats">
      <span class="stat"><strong>{total_episodes}</strong> episodes</span>
      <span class="stat"><strong>{total_weeks}</strong> weeks tracked</span>
    </div>
  </div>
</div>

<main>
{weeks_html}
{empty_msg}
</main>

<footer>
  <div class="footer-inner">
    <p>Summaries generated by Claude AI · Transcripts via Whisper &amp; YouTube</p>
    <p>Sources:
    <a href="https://open.spotify.com/show/0WrBZujO7cbhbaqsNCEbTu" target="_blank">The Credit Edge</a> ·
    <a href="https://open.spotify.com/show/1te7oSFyRVekxMBJUSethH" target="_blank">Odd Lots</a> ·
    <a href="https://www.apolloacademy.com/the-view-from-apollo/" target="_blank">The View from Apollo</a> ·
    <a href="https://open.spotify.com/show/6UllvbuIsyPESs38EWPanH" target="_blank">Oaktree Insight</a> ·
    <a href="https://www.youtube.com/@GoldmanSachs" target="_blank">Goldman Sachs</a> ·
    <a href="https://www.youtube.com/channel/UCbzQ_YWf9RsBP9ATbmv5kxQ" target="_blank">Capital Allocators</a>
    </p>
  </div>
</footer>

<script>
{js}
</script>
</body>
</html>
"""

# ---------------------------------------------------------------------------
# CSS
# ---------------------------------------------------------------------------

_CSS = """\
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

:root {
  --bg:          #0d1117;
  --bg-card:     #161b22;
  --bg-card-2:   #1c2230;
  --border:      #30363d;
  --border-soft: #21262d;
  --text:        #e6edf3;
  --text-muted:  #8b949e;
  --text-dim:    #6e7681;
  --accent:      #58a6ff;
  --accent-glow: rgba(88,166,255,.15);
  --green:       #3fb950;
  --radius:      10px;
  --radius-sm:   6px;
  --shadow:      0 4px 24px rgba(0,0,0,.4);
  font-size: 15px;
}

body {
  background: var(--bg);
  color: var(--text);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
  line-height: 1.6;
  min-height: 100vh;
}

a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }

/* ── Header ── */
header {
  background: linear-gradient(135deg, #0d1117 0%, #161b22 100%);
  border-bottom: 1px solid var(--border);
  padding: 28px 0;
}
.header-inner {
  max-width: 1100px;
  margin: 0 auto;
  padding: 0 24px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  flex-wrap: wrap;
}
.header-brand { display: flex; align-items: center; gap: 16px; }
.brand-icon {
  font-size: 2.2rem;
  color: var(--accent);
  filter: drop-shadow(0 0 8px var(--accent-glow));
  line-height: 1;
}
h1 { font-size: 1.7rem; font-weight: 700; letter-spacing: -.3px; }
.tagline { color: var(--text-muted); font-size: .85rem; margin-top: 2px; }
.header-meta { text-align: right; }
.updated-label { display: block; font-size: .75rem; color: var(--text-dim); text-transform: uppercase; letter-spacing: .05em; }
.updated-date { font-size: .9rem; color: var(--text-muted); }

/* ── Controls ── */
.controls {
  background: var(--bg-card);
  border-bottom: 1px solid var(--border-soft);
  position: sticky;
  top: 0;
  z-index: 50;
}
.controls-inner {
  max-width: 1100px;
  margin: 0 auto;
  padding: 12px 24px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  flex-wrap: wrap;
}
.filter-group { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; }
.filter-label { font-size: .8rem; color: var(--text-dim); white-space: nowrap; }
.filter-btns { display: flex; gap: 6px; flex-wrap: wrap; }
.filter-btn {
  padding: 5px 14px;
  border-radius: 20px;
  border: 1px solid var(--border);
  background: transparent;
  color: var(--text-muted);
  font-size: .8rem;
  cursor: pointer;
  transition: all .15s;
}
.filter-btn:hover { border-color: var(--accent); color: var(--accent); }
.filter-btn.active { background: var(--accent); border-color: var(--accent); color: #fff; font-weight: 600; }
.stats { display: flex; gap: 16px; }
.stat { font-size: .82rem; color: var(--text-muted); }
.stat strong { color: var(--text); }

/* ── Main ── */
main {
  max-width: 1100px;
  margin: 0 auto;
  padding: 32px 24px 64px;
}

/* ── Week section ── */
.week-section { margin-bottom: 48px; }
.week-section.hidden { display: none; }

.week-header {
  display: flex;
  align-items: baseline;
  gap: 14px;
  margin-bottom: 20px;
  padding-bottom: 12px;
  border-bottom: 1px solid var(--border-soft);
}
.week-label {
  font-size: .75rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: .08em;
  color: var(--accent);
  background: var(--accent-glow);
  padding: 3px 10px;
  border-radius: 20px;
  border: 1px solid rgba(88,166,255,.3);
}
.week-date-range { font-size: .85rem; color: var(--text-muted); }
.week-count { font-size: .8rem; color: var(--text-dim); margin-left: auto; }

/* ── Episode grid ── */
.episode-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(480px, 1fr));
  gap: 16px;
}

/* ── Episode card ── */
.episode-card {
  background: var(--bg-card);
  border: 1px solid var(--border-soft);
  border-radius: var(--radius);
  overflow: hidden;
  transition: border-color .2s, box-shadow .2s;
}
.episode-card:hover { border-color: var(--border); box-shadow: var(--shadow); }
.episode-card.filtered-out { display: none; }

.card-top {
  padding: 18px 20px 0;
}

.card-meta {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 10px;
}

.source-badge {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  font-size: .72rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: .06em;
  padding: 3px 10px;
  border-radius: 20px;
  border: 1px solid;
}

.ep-date { font-size: .78rem; color: var(--text-dim); }
.ep-type-badge {
  font-size: .68rem;
  padding: 2px 7px;
  border-radius: 4px;
  background: var(--border-soft);
  color: var(--text-dim);
  text-transform: uppercase;
  letter-spacing: .05em;
}

.card-title {
  font-size: 1rem;
  font-weight: 600;
  line-height: 1.4;
  margin-bottom: 10px;
  color: var(--text);
}

.one-liner {
  font-size: .88rem;
  color: var(--text-muted);
  font-style: italic;
  margin-bottom: 14px;
  padding-left: 10px;
  border-left: 2px solid var(--border);
}

.themes {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-bottom: 14px;
}
.theme-tag {
  font-size: .72rem;
  padding: 2px 9px;
  border-radius: 20px;
  background: var(--bg-card-2);
  border: 1px solid var(--border-soft);
  color: var(--text-muted);
}

/* ── Two-pass takeaways ── */
.takeaways {
  border-top: 1px solid var(--border-soft);
}
.pass-section {
  padding: 12px 20px;
}
.pass-section + .pass-section {
  border-top: 1px solid var(--border-soft);
}
.pass-title {
  font-size: .72rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: .07em;
  margin-bottom: 8px;
  display: flex;
  align-items: center;
  gap: 5px;
}
.market-pass { background: rgba(245,158,11,.05); }
.market-pass .pass-title { color: #f59e0b; }
.market-pass li::before { color: #f59e0b; }
.framework-pass { background: rgba(56,189,248,.05); }
.framework-pass .pass-title { color: #38bdf8; }
.framework-pass li::before { color: #38bdf8; }
.takeaways ul { list-style: none; display: flex; flex-direction: column; gap: 5px; }
.takeaways li {
  font-size: .84rem;
  color: var(--text-muted);
  padding-left: 16px;
  position: relative;
}
.takeaways li::before {
  content: "→";
  position: absolute;
  left: 0;
  font-size: .8rem;
}
/* fallback for old episodes with key_takeaways */
.takeaways-legacy { padding: 14px 20px; background: var(--bg-card-2); }
.takeaways-title {
  font-size: .72rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: .07em;
  color: var(--text-dim);
  margin-bottom: 8px;
}
.takeaways-legacy li::before { color: var(--accent); }

/* ── Expandable full summary ── */
.card-expand {
  padding: 0 20px;
  overflow: hidden;
  max-height: 0;
  transition: max-height .3s ease, padding .3s ease;
}
.card-expand.open {
  max-height: 1000px;
  padding: 14px 20px;
}
.expand-inner { border-top: 1px solid var(--border-soft); padding-top: 14px; }
.expand-label {
  font-size: .72rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: .07em;
  color: var(--text-dim);
  margin-bottom: 8px;
}
.summary-text { font-size: .88rem; color: var(--text-muted); line-height: 1.7; white-space: pre-line; }
.market-rel {
  margin-top: 12px;
  padding: 10px 14px;
  background: rgba(63,185,80,.08);
  border: 1px solid rgba(63,185,80,.2);
  border-radius: var(--radius-sm);
  font-size: .84rem;
  color: #8ee09a;
}
.market-rel-label {
  font-size: .7rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: .06em;
  color: var(--green);
  margin-bottom: 4px;
}

/* ── Card footer ── */
.card-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 20px;
  border-top: 1px solid var(--border-soft);
  gap: 8px;
}
.btn-expand {
  background: transparent;
  border: 1px solid var(--border);
  color: var(--text-muted);
  font-size: .8rem;
  padding: 5px 14px;
  border-radius: 6px;
  cursor: pointer;
  transition: all .15s;
}
.btn-expand:hover { border-color: var(--accent); color: var(--accent); }
.btn-listen {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  font-size: .8rem;
  padding: 5px 14px;
  border-radius: 6px;
  border: 1px solid var(--border);
  color: var(--text-muted);
  transition: all .15s;
}
.btn-listen:hover { border-color: var(--accent); color: var(--accent); text-decoration: none; }
.transcript-len { font-size: .72rem; color: var(--text-dim); }

/* ── Empty state ── */
.empty-state {
  text-align: center;
  padding: 80px 24px;
  color: var(--text-muted);
}
.empty-state h2 { font-size: 1.2rem; margin-bottom: 8px; color: var(--text); }

/* ── Footer ── */
footer {
  background: var(--bg-card);
  border-top: 1px solid var(--border-soft);
  padding: 24px 0;
}
.footer-inner {
  max-width: 1100px;
  margin: 0 auto;
  padding: 0 24px;
  display: flex;
  flex-direction: column;
  gap: 4px;
  align-items: center;
  text-align: center;
  color: var(--text-dim);
  font-size: .8rem;
}

/* ── Responsive ── */
@media (max-width: 640px) {
  .episode-grid { grid-template-columns: 1fr; }
  h1 { font-size: 1.3rem; }
  .controls-inner { flex-direction: column; align-items: flex-start; }
  .stats { display: none; }
}
"""

# ---------------------------------------------------------------------------
# JavaScript
# ---------------------------------------------------------------------------

_JS = """\
(function () {
  // Source filter
  const filterBtns = document.querySelectorAll('.filter-btn');
  const cards = document.querySelectorAll('.episode-card');
  const weekSections = document.querySelectorAll('.week-section');

  filterBtns.forEach(btn => {
    btn.addEventListener('click', () => {
      filterBtns.forEach(b => b.classList.remove('active'));
      btn.classList.add('active');
      const src = btn.dataset.source;

      cards.forEach(card => {
        if (src === 'all' || card.dataset.source === src) {
          card.classList.remove('filtered-out');
        } else {
          card.classList.add('filtered-out');
        }
      });

      // Hide weeks that have no visible cards
      weekSections.forEach(section => {
        const visible = section.querySelectorAll('.episode-card:not(.filtered-out)');
        section.classList.toggle('hidden', visible.length === 0);
      });
    });
  });

  // Expand / collapse full summary
  document.querySelectorAll('.btn-expand').forEach(btn => {
    btn.addEventListener('click', () => {
      const card = btn.closest('.episode-card');
      const panel = card.querySelector('.card-expand');
      const open = panel.classList.toggle('open');
      btn.textContent = open ? 'Hide Summary ▲' : 'Full Summary ▼';
    });
  });
})();
"""

# ---------------------------------------------------------------------------
# Rendering helpers
# ---------------------------------------------------------------------------

def _week_date_range(week_str: str) -> str:
    """Convert '2024-W03' to 'Jan 15 – Jan 21, 2024'."""
    try:
        year, w = week_str.split("-W")
        mon = datetime.fromisocalendar(int(year), int(w), 1)
        sun = datetime.fromisocalendar(int(year), int(w), 7)
        if mon.month == sun.month:
            return f"{mon.strftime('%b')} {mon.day} – {sun.day}, {sun.strftime('%Y')}"
        return f"{mon.strftime('%b')} {mon.day} – {sun.strftime('%b')} {sun.day}, {sun.strftime('%Y')}"
    except Exception:
        return week_str


def _badge_style(color: str) -> str:
    return f'style="color:{color};border-color:{color};background:rgba(0,0,0,.3)"'


def _render_takeaways(market_signals: list, framework_insights: list, key_takeaways: list) -> str:
    if market_signals or framework_insights:
        signals_html = "".join(f"<li>{s}</li>" for s in market_signals)
        insights_html = "".join(f"<li>{i}</li>" for i in framework_insights)
        signals_block = f'<div class="pass-section market-pass"><div class="pass-title">&#9889; Market Signals</div><ul>{signals_html}</ul></div>' if signals_html else ""
        insights_block = f'<div class="pass-section framework-pass"><div class="pass-title">&#128161; Framework Insights</div><ul>{insights_html}</ul></div>' if insights_html else ""
        return f'<div class="takeaways">{signals_block}{insights_block}</div>' if (signals_block or insights_block) else ""
    if key_takeaways:
        items = "".join(f"<li>{t}</li>" for t in key_takeaways)
        return f'<div class="takeaways takeaways-legacy"><div class="takeaways-title">Key Takeaways</div><ul>{items}</ul></div>'
    return ""


def _render_card(ep: dict) -> str:
    meta = _SOURCE_META.get(ep.get("source_id", ""), {"label": ep.get("source_name", ""), "icon": "◉"})
    color = ep.get("source_color", "#58a6ff")
    source_id = ep.get("source_id", "")
    ep_type = ep.get("type", "podcast")
    type_label = "YouTube" if ep_type == "youtube" else "Podcast"

    themes_html = "".join(f'<span class="theme-tag">{t}</span>' for t in ep.get("key_themes", []))
    summary = ep.get("summary", "")
    market_rel = ep.get("market_relevance", "")
    one_liner = ep.get("one_line_summary", "")
    transcript_len = ep.get("transcript_length", 0)
    tlen_str = f"{transcript_len // 1000}k chars" if transcript_len else ""

    market_signals = ep.get("market_signals", [])
    framework_insights = ep.get("framework_insights", [])
    key_takeaways = ep.get("key_takeaways", [])

    market_html = ""
    if market_rel:
        market_html = f"""
      <div class="market-rel">
        <div class="market-rel-label">Market Relevance</div>
        {market_rel}
      </div>"""

    expand_html = ""
    if summary:
        expand_html = f"""
  <div class="card-expand">
    <div class="expand-inner">
      <div class="expand-label">Full Summary</div>
      <div class="summary-text">{summary}</div>{market_html}
    </div>
  </div>"""

    return f"""
<article class="episode-card" data-source="{source_id}">
  <div class="card-top">
    <div class="card-meta">
      <span class="source-badge" {_badge_style(color)}>{meta['icon']} {meta['label']}</span>
      <div style="display:flex;gap:8px;align-items:center">
        <span class="ep-type-badge">{type_label}</span>
        <span class="ep-date">{ep.get('published', '')}</span>
      </div>
    </div>
    <h2 class="card-title">{ep.get('title', 'Untitled')}</h2>
    {f'<p class="one-liner">{one_liner}</p>' if one_liner else ''}
    {f'<div class="themes">{themes_html}</div>' if themes_html else ''}
  </div>

  {_render_takeaways(market_signals, framework_insights, key_takeaways)}
  {expand_html}

  <div class="card-footer">
    {'<button class="btn-expand">Full Summary ▼</button>' if summary else '<span></span>'}
    <div style="display:flex;align-items:center;gap:12px">
      {f'<span class="transcript-len">{tlen_str}</span>' if tlen_str else ''}
      <a class="btn-listen" href="{ep.get('episode_url', '#')}" target="_blank">
        {'▶ Watch' if ep_type == 'youtube' else '🎧 Listen'}
      </a>
    </div>
  </div>
</article>"""


def _render_week(week_str: str, episodes: list[dict]) -> str:
    date_range = _week_date_range(week_str)
    cards_html = "\n".join(_render_card(ep) for ep in episodes)
    count = len(episodes)
    return f"""
<section class="week-section" data-week="{week_str}">
  <div class="week-header">
    <span class="week-label">{week_str}</span>
    <span class="week-date-range">{date_range}</span>
    <span class="week-count">{count} episode{'s' if count != 1 else ''}</span>
  </div>
  <div class="episode-grid">
{cards_html}
  </div>
</section>"""


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def generate_html(output_path: Path, episodes: list[dict]) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Group by week, newest first
    episodes_sorted = sorted(episodes, key=lambda e: e.get("published", ""), reverse=True)
    weeks_html = ""
    total_weeks = 0

    for week, group in groupby(episodes_sorted, key=lambda e: e.get("week", "Unknown")):
        eps_in_week = list(group)
        weeks_html += _render_week(week, eps_in_week)
        total_weeks += 1

    empty_msg = ""
    if not episodes:
        empty_msg = """
<div class="empty-state">
  <h2>No episodes yet</h2>
  <p>Run the tracker script to fetch and summarize the latest episodes.</p>
</div>"""

    now = datetime.now(timezone.utc)
    updated = f"{now.strftime('%B')} {now.day}, {now.strftime('%Y at %H:%M UTC')}"
    html = _HTML.format(
        css=_CSS,
        js=_JS,
        updated=updated,
        total_episodes=len(episodes),
        total_weeks=total_weeks,
        weeks_html=weeks_html,
        empty_msg=empty_msg,
    )

    output_path.write_text(html, encoding="utf-8")
    print(f"  HTML report: {len(episodes)} episodes across {total_weeks} weeks → {output_path}")
